services:
  stats-db:
    image: postgres:15
    container_name: stats-db
    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: stats_user
      POSTGRES_PASSWORD: stats_password
    volumes:
      - stats-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - stats-network

  stats-server:
    build: stats-server/stats-service-server
    image: stats-service-server-image
    container_name: stats-service-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats
      SPRING_DATASOURCE_USERNAME: stats_user
      SPRING_DATASOURCE_PASSWORD: stats_password
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    networks:
      - stats-network

  ewm-service:
    build: ewm-service
    image: ewm-service-image
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5431/ewm
      - POSTGRES_USER=ewm_user
      - POSTGRES_PASSWORD=ewm_password

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6542:5431"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=ewm_user
      - POSTGRES_PASSWORD=ewm_password